#ifndef _COSMOS_ERROR_H
#define _COSMOS_ERROR_H

#include <errno.h>

#define ASTRODEV_ERROR_HEADER_CS -431
#define ASTRODEV_ERROR_SYNC0 -432
#define ASTRODEV_ERROR_NACK -433
#define ASTRODEV_ERROR_PAYLOAD_CS -434
#define ASTRODEV_ERROR_SYNC1 -435
#define ASTRODEV_ERROR_HEADER -436
#define ASTRODEV_ERROR_PAYLOAD -437

#endif // _COSMOS_ERROR_H
